name:                brainfuck-haskell-v2
version:             0.1.0.0
github:              "githubuser/brainfuck-haskell-v2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/brainfuck-haskell-v2#readme>

dependencies:
- base >= 4.7 && < 5
- relude # alternative prelude
- free # free monads
- mtl # we actually need this only for Cont
# miscellaneous packages
- text
- directory

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - LambdaCase
  - RankNTypes
  - DeriveGeneric
  - DeriveAnyClass
  - GADTs
  - StandaloneDeriving
  - RecordWildCards
  - ConstraintKinds
  - TypeApplications
  - ViewPatterns
  - TupleSections
  - ScopedTypeVariables

library:
  source-dirs: src

executables:
  brainfuck-haskell-v2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfuck-haskell-v2

tests:
  brainfuck-haskell-v2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfuck-haskell-v2
    - hspec
    - QuickCheck
