on:
  push:
    paths:
      - '**.hs'
      - 'package.yaml'
      - 'stack.yaml'

name: build

jobs:
  buildapp:
    name: Build Brainfuck Interpreter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v1
        name: Setup Haskell Stack
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v3.0.2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --system-ghc
